# This is a basic workflow to help you get started with Actions

name: Auto pull request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: add ssh key
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.DEPLOY_KEY }}'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository: rubennaatje/dependent
      - name: Set branch
        run: git switch -c update-protos 
        
      - name: 'update package'
        run:  npx npm-check-updates @ruben/autoUpdate -u

      - name: 'install packages'
        run:  npm install
      - name: 'Git things'
        run: |
          git config --global user.email "protoupdater@github.com"
          git config --global user.name "proto updater"
      - name: 'Add package.json & package-lock.json'
        run: git add package-lock.json package.json
      
      - name: 'Commit'
        run: git commit -m "update protos automatically"
        
      - name: 'Push'
        run: git push origin update-protos --set-upstream --force
