# This workflow automatically updates the @ptibv/protos package in the BiHook repo

name: Auto pull request

# Controls when the workflow will run
on:
  # on push event for a new version tag
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  # Or manually run this workflow from the workflow tab in github
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Add ssh key to agent
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.DEPLOY_KEY }}'
      
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository: rubennaatje/dependent

      - name: 'Update package'
        run:  npx npm-check-updates @ruben/autoUpdate -u

      - name: 'Install packages'
        run:  npm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update protos
          title: Update Protos
          body: Update Protos to newly released version
          branch: update-protos
          base: master
          token: ${{ secrets.PAT }}
